name: Deploy Staging App
run-name: ${{ gitea.actor }} is deploying the app 🚀
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          GIT_TERMINAL_PROMPT: '0'

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        shell: bash
        run: npm install -g yarn node-gyp

      - name: Prepare node_modules
        shell: bash
        run: yarn install
