name: Deploy Staging App
run-name: ${{ gitea.actor }} is deploying the app 🚀
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare node_modules
        shell: bash
        run: yarn install
