name: Deploy Staging App
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Kubeconfig
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BUILDX }}" > $HOME/.kube/config

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=lof
            qemu.install=true

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.djmeph.net
          username: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/digital-www/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/djmeph/lof-digital-www
          cache-to: type=registry,ref=ghcr.io/djmeph/lof-digital-www:buildcache,mode=max
          cathe-from: type=registry,ghcr.io/djmeph/lof-digital-www:buildcache
