name: Deploy Staging App
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          qemu: true

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: djmeph
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build app
        shell: bash
        run: |
          yarn install
          yarn nx run digital-www:build:production

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/digital-www/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/djmeph/lof-digital-www
          cache-from: type=registry,ref=ghcr.io/djmeph/lof-digital-www:buildcache
          cache-to: type=registry,ref=ghcr.io/djmeph/lof-digital-www:buildcache,mode=max
